version: '3.8'

services:
  bloop-playground:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloop-playground-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
