server.port=8080
spring.application.name=bloop-interpreter-backend
# Support handling static files in resources/static (fallback for frontend)
spring.web.resources.static-locations=classpath:/static/
